// src/components/ConfigColor.vue
<template>
  <section class="config-color">
    <div v-for="item in colorList" :key="item.key" class="color-item">
      <input v-model="modelValue[item.key]" type="color" class="input">
      <span class="text" @click="reset(item)">{{ item.name }}</span>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent, toRefs } from 'vue'
import { colorList } from './../config'
import { ConfigColorItem } from './../types/index'

export default defineComponent({
  name: 'ConfigColor',
  props: {
    modelValue: {
      type: Object,
      required: true,
    },
  },
  setup(props) {
    const { modelValue } = toRefs(props)

    function reset(item: ConfigColorItem) {
      modelValue.value[item.key] = item.value
    }

    return {
      colorList,
      modelValue,
      reset,
    }
  }
})
</script>

<style>
.config-color {
  position: fixed;
  right: 0;
  bottom: 0;
  z-index: 10;
  padding: 0 20px 20px 0;
}
.config-color .color-item {
  display: flex;
  align-items: center;
}
.config-color .color-item .input {
  width: 40px;
  height: 25px;
  border: 0;
  background-color: transparent;
  cursor: pointer;
}
.config-color .color-item .text {
  margin-left: 6px;
  cursor: pointer;
}
@media screen and (max-width:500px) {
  .config-color {
    padding: 0 10px 10px 0;
  }
  .config-color .color-item .input {
    width: 30px;
    height: 20px;
  }
}
</style>

// src/components/ConfigColor/index.tsx
import { For } from 'solid-js'
import { colorList } from '../../config'
import { ConfigColorItem, LocalColor } from '../../types/index'
import type { SetStoreFunction } from 'solid-js/store'
import './index.css'

interface Props {
  value: LocalColor
  onChange: SetStoreFunction<LocalColor>
}

export default function ConfigColor(props: Props) {
  function change(event: Event, item: ConfigColorItem) {
    const target = event.target as HTMLInputElement
    props.onChange({ [item.key]: target?.value })
  }

  function reset(item: ConfigColorItem) {
    props.onChange({ [item.key]: item.value })
  }

  return (
    <section class="config-color">
      <For each={colorList}>
        {(item) => (
          <div class="color-item">
            <input
              value={props.value[item.key]}
              type="color"
              class="input"
              onChange={(e: Event) => change(e, item)}
            />
            <span class="text" onClick={() => reset(item)}>
              {item.name}
            </span>
          </div>
        )}
      </For>
    </section>
  )
}
