// src/App.tsx
import { batch, createMemo, onMount } from 'solid-js'
import {
  useColorList,
  useControl,
  useLoadMapData,
  useMapList
} from './hooks/index'
import Header from './components/Header/index'
import Serach from './components/Serach/index'
import Select from './components/Select/index'
import Map from './components/Map/index'
import ConfigColor from './components/ConfigColor/index'
import Footer from './components/Footer/index'
import TipMessage from './components/TipMessage/index'
import TipPoint from './components/TipPoint/index'
import { MapPoint } from './types/index'

export default function App() {
  const [color, setColor] = useColorList()
  const [type, setType] = useMapList()
  const mapData = useLoadMapData(type)
  const { data, setData, setTransform } = useControl(mapData)

  const style = createMemo(() => ({
    ...color,
    '--size-stroke': 1 / data.relativeScale,
    transform: data.transform,
  }))

  onMount(() => {
    document.querySelector('#app .loading')?.remove()
  })

  function refresh(value: string) {
    batch(() => {
      setType(value)
      setData({
        x: 0,
        y: 0,
        scale: 1,
        transform: '',
      })
    })
  }

  function moveMap(poit: MapPoint) {
    const x = -(poit.x - mapData().center.x) * data.relativeScale
    const y = -(poit.z - mapData().center.z) * data.relativeScale

    batch(() => {
      setData({ x, y })
      setTransform(x, y, data.scale)
    })
  }

  return <>
    <Header title={mapData().title}>
      <Serach onMove={moveMap}/>
      <Select value={type()} onChange={refresh} />
    </Header>
    <Map
      data={mapData()}
      loading={mapData.loading}
      message={data.pointMessage}
      style={style()}
      onOverPath={setData}
    />
    <ConfigColor value={color} onChange={setColor} />
    <Footer uptime={mapData().uptime} author={mapData().author} />
    <TipMessage
      loading={mapData.loading}
      type={type()}
      version={mapData().version}
      introduce={mapData().introduce}
    />
    <TipPoint message={data.pointMessage} style={data.pointStyle} />
  </>
}

// src/App.vue
<template>
  <app-header :title="mapData.title">
    <serach-box :nameList="nameList" @move-map="moveMap" />
    <select-source v-model="type" />
  </app-header>
  <app-svg :data="mapData" :loading="loading" :style="style" @nameList="setNameList" />
  <config-color v-model="color" />
  <app-footer :uptime="mapData.uptime" :author="mapData.author" />
  <tip-message :type="type" :version="mapData.version" :introduce="mapData.introduce" />
</template>

<script lang="ts">
import { computed, ref, watch } from 'vue'
import { useColorList, useControl, useMapList } from './composables/index.ts'
import { get } from './utils/index.ts'
import { MapData, MapNameItem, MapPoint } from './types/index.d.ts'
import AppHeader from './components/AppHeader.vue'
import AppSvg from './components/AppSvg.vue'
import AppFooter from './components/AppFooter.vue'
import SerachBox from './components/SerachBox.vue'
import SelectSource from './components/SelectSource.vue'
import ConfigColor from './components/ConfigColor.vue'
import TipMessage from './components/TipMessage.vue'

export default {
  name: 'App',
  components: {
    AppHeader,
    AppSvg,
    AppFooter,
    SerachBox,
    SelectSource,
    ConfigColor,
    TipMessage,
  },
  setup () {
    const color = useColorList()
    const type = useMapList()
    const path = computed(() => `/config/${type.value}.json`)
    const loading = ref(true)
    const mapData = ref<MapData>({})
    const nameList = ref<MapNameItem[]>([])
    const { x, y, s, leastWidth, transform, setTransform } = useControl()
    const style = computed(() => ({
      ...color.value,
      '--size-stroke': mapData.value.radius / leastWidth.value / s.value,
      transform: transform.value,
    }))

    getMapData()

    watch(type, getMapData)

    async function getMapData() {
      loading.value = true
      x.value = 0
      y.value = 0
      s.value = 1
      transform.value = ''
      mapData.value = {}
      mapData.value = await get<MapData>(path.value)
    }

    function setNameList(value: MapNameItem[]) {
      loading.value = false
      nameList.value = value
    }

    function moveMap(poit: MapPoint) {
      const _s = -0.45 * s.value * leastWidth.value / mapData.value.radius
      x.value = _s * poit.x
      y.value = _s * poit.z
      setTransform(x.value, y.value, s.value)
    }

    return {
      type,
      color,
      loading,
      mapData,
      nameList,
      setNameList,
      style,
      moveMap,
    }
  }
}
</script>
